import type { TestScenario } from '@/hooks/useBookingFlowTest';

export const HAPPY_PATH_SCENARIOS: TestScenario[] = [
  {
    id: 'nyc-small-tester',
    name: 'NYC Small Home - Tester Deep Clean',
    description: 'NYC 1000-1499 sqft home with Tester Deep Clean offer',
    zipCode: '10001',
    homeSize: '1000-1499',
    serviceType: 'deep-cleaning',
    frequency: 'one-time',
    expectedPrice: 250,
    expectedDeposit: 62.5,
  },
  {
    id: 'nyc-medium-90day',
    name: 'NYC Medium Home - 90-Day Plan',
    description: 'NYC 1500-1999 sqft home with 90-Day Plan',
    zipCode: '10002',
    homeSize: '1500-1999',
    serviceType: 'deep-cleaning',
    frequency: '90-day-plan',
    expectedPrice: 799,
    expectedDeposit: 199.75,
  },
  {
    id: 'brooklyn-large-tester',
    name: 'Brooklyn Large Home - Tester Deep Clean',
    description: 'Brooklyn 2000-2499 sqft home with Tester Deep Clean',
    zipCode: '11201',
    homeSize: '2000-2499',
    serviceType: 'deep-cleaning',
    frequency: 'one-time',
    expectedPrice: 350,
    expectedDeposit: 87.5,
  },
  {
    id: 'long-island-xlarge-90day',
    name: 'Long Island Extra Large Home - 90-Day Plan',
    description: 'Long Island 2500-2999 sqft home with 90-Day Plan',
    zipCode: '11501',
    homeSize: '2500-2999',
    serviceType: 'deep-cleaning',
    frequency: '90-day-plan',
    expectedPrice: 1099,
    expectedDeposit: 274.75,
  },
  {
    id: 'queens-small-tester',
    name: 'Queens Small Home - Tester Deep Clean',
    description: 'Queens 1000-1499 sqft home with Tester Deep Clean',
    zipCode: '11101',
    homeSize: '1000-1499',
    serviceType: 'deep-cleaning',
    frequency: 'one-time',
    expectedPrice: 250,
    expectedDeposit: 62.5,
  },
];

export const EDGE_CASE_SCENARIOS: TestScenario[] = [
  {
    id: 'invalid-zip',
    name: 'Invalid ZIP Code',
    description: 'Test ZIP code validation with invalid format',
    zipCode: '00000',
    homeSize: '1500-1999',
    serviceType: 'deep-cleaning',
    frequency: 'one-time',
  },
  {
    id: 'unsupported-area',
    name: 'Unsupported Service Area',
    description: 'ZIP code outside New York State',
    zipCode: '90210',
    homeSize: '1500-1999',
    serviceType: 'deep-cleaning',
    frequency: 'one-time',
  },
  {
    id: 'very-large-home',
    name: 'Very Large Home (5000+ sqft)',
    description: 'Test custom estimate flow for homes requiring quotes',
    zipCode: '10024',
    homeSize: '5000+',
    serviceType: 'deep-cleaning',
    frequency: 'one-time',
    expectedPrice: 550,
    expectedDeposit: 137.5,
  },
];

export const ALL_TEST_SCENARIOS = [...HAPPY_PATH_SCENARIOS, ...EDGE_CASE_SCENARIOS];
